### ISSUE TITLE
Is the 16 GB image necessary?

### ISSUE THREAD

**Issue by 0x779** [PaulJenkin/PS4Pizero#2]
Can it be cut down to size, maybe to fit in an 8 GB microSD?

**Comment by PaulJenkin** [comment]
Nope 16 gb not required
Working on 300 mb  one
You can expect more detailed write up and version 5 in 2 days
Also additional image which supports pi 4

**Comment by 0x779** [comment]
That's awesome news! Looking forward to it.

**Comment by PaulJenkin** [comment]
https://1fichier.com/?rb9uj9b5ujg0kee0slg3 - V4
